### ISSUE TITLE
Missing default VID:PID on macos

### ISSUE THREAD

**Issue by gmcgarry** [accesio/fxload#1]
Easier for me to post the diff than confuse the world with yet another fork of fxload on github.  With this change, fxload on macos aligns with the documentation.

`$ git diff
diff --git a/macos/main.m b/macos/main.m
index ec6b728..f7180e8 100644
--- a/macos/main.m
+++ b/macos/main.m
@@ -122,6 +122,9 @@ static int findDevice(IOUSBDeviceInterface*** dev, NSNumber* vid, NSNumber* pid)
 {
     int opt;
     NSMutableDictionary* args = [NSMutableDictionary dictionary];
+
+    [args setValue:[NSNumber numberWithUnsignedInt:0x04b4] forKey:kArgVid];
+    [args setValue:[NSNumber numberWithUnsignedInt:0x8613] forKey:kArgPid];
     
     *result = TRUE;
`

**Comment by jdolanIV** [comment]
I think the diff got truncated or something. It's also strange that it says the hunk is in findDevice(), but the context is parseArgs().
